version: "3.7"
services:
  builder:
    build:
      context: ./
      dockerfile: ./docker/build.dockerfile
    volumes:
      - ./:/var/program
  node:
    build:
      context: ./
      dockerfile: ./docker/run.dockerfile
