#include <fiberchain/protocol/get_config.hpp>
#include <fiberchain/protocol/config.hpp>
#include <fiberchain/protocol/asset.hpp>
#include <fiberchain/protocol/types.hpp>
#include <fiberchain/protocol/version.hpp>

namespace fiberchain { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

   result[ "IS_TEST_NET" ] = true;
   result["SNAC_SYMBOL"] = SNAC_SYMBOL;
   result["FIBERCHAIN_100_PERCENT"] = FIBERCHAIN_100_PERCENT;
   result["FIBERCHAIN_1_PERCENT"] = FIBERCHAIN_1_PERCENT;
   result["FIBERCHAIN_1_TENTH_PERCENT"] = FIBERCHAIN_1_TENTH_PERCENT;
   result["FIBERCHAIN_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = FIBERCHAIN_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["FIBERCHAIN_ADDRESS_PREFIX"] = FIBERCHAIN_ADDRESS_PREFIX;
   result["FIBERCHAIN_BLOCKCHAIN_PRECISION_DIGITS"] = FIBERCHAIN_BLOCKCHAIN_PRECISION_DIGITS;
   result["FIBERCHAIN_BLOCKCHAIN_SNAC_PRECISION_DIGITS"] = FIBERCHAIN_BLOCKCHAIN_SNAC_PRECISION_DIGITS;
   result["FIBERCHAIN_BLOCKCHAIN_HARDFORK_VERSION"] = FIBERCHAIN_BLOCKCHAIN_HARDFORK_VERSION;
   result["FIBERCHAIN_BLOCKCHAIN_VERSION"] = FIBERCHAIN_BLOCKCHAIN_VERSION;
   result["FIBERCHAIN_BLOCK_INTERVAL"] = FIBERCHAIN_BLOCK_INTERVAL;
   result["FIBERCHAIN_BLOCKS_PER_DAY"] = FIBERCHAIN_BLOCKS_PER_DAY;
   result["FIBERCHAIN_BLOCKS_PER_YEAR"] = FIBERCHAIN_BLOCKS_PER_YEAR;
   result["FIBERCHAIN_CHAIN_ID"] = FIBERCHAIN_CHAIN_ID;
   result["FIBERCHAIN_CREATE_ACCOUNT_DELEGATION_RATIO"] = FIBERCHAIN_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["FIBERCHAIN_CREATE_ACCOUNT_WITH_FIBERCHAIN_MODIFIER"] = FIBERCHAIN_CREATE_ACCOUNT_WITH_FIBERCHAIN_MODIFIER;
   result["FIBERCHAIN_GENESIS_TIME"] = FIBERCHAIN_GENESIS_TIME;
   result["FIBERCHAIN_HARDFORK_REQUIRED_BOBSERVERS"] = FIBERCHAIN_HARDFORK_REQUIRED_BOBSERVERS;
   result["FIBERCHAIN_INIT_MINER_NAME"] = FIBERCHAIN_INIT_MINER_NAME;
   result["FIBERCHAIN_INIT_PUBLIC_KEY_STR"] = FIBERCHAIN_INIT_PUBLIC_KEY_STR;
   result["FIBERCHAIN_INIT_PRIVATE_KEY"] = FIBERCHAIN_INIT_PRIVATE_KEY;
   result["FIBERCHAIN_INIT_SUPPLY"] = FIBERCHAIN_INIT_SUPPLY;
   result["FIBERCHAIN_INIT_TIME"] = FIBERCHAIN_INIT_TIME;
   result["FIBERCHAIN_IRREVERSIBLE_THRESHOLD"] = FIBERCHAIN_IRREVERSIBLE_THRESHOLD;
   result["FIBERCHAIN_MAX_ACCOUNT_NAME_LENGTH"] = FIBERCHAIN_MAX_ACCOUNT_NAME_LENGTH;
   result["FIBERCHAIN_MAX_ACCOUNT_BOBSERVER_VOTES"] = FIBERCHAIN_MAX_ACCOUNT_BOBSERVER_VOTES;
   result["FIBERCHAIN_MAX_BLOCK_SIZE"] = FIBERCHAIN_MAX_BLOCK_SIZE;
   result["FIBERCHAIN_MAX_COMMENT_DEPTH"] = FIBERCHAIN_MAX_COMMENT_DEPTH;
   result["FIBERCHAIN_MAX_MEMO_SIZE"] = FIBERCHAIN_MAX_MEMO_SIZE;
   result["FIBERCHAIN_MAX_BOBSERVERS"] = FIBERCHAIN_MAX_BOBSERVERS;
   result["FIBERCHAIN_MAX_MINER_BOBSERVERS_HF0"] = FIBERCHAIN_MAX_MINER_BOBSERVERS_HF0;
   result["FIBERCHAIN_MAX_PERMLINK_LENGTH"] = FIBERCHAIN_MAX_PERMLINK_LENGTH;
   result["FIBERCHAIN_MAX_RESERVE_RATIO"] = FIBERCHAIN_MAX_RESERVE_RATIO;
   result["FIBERCHAIN_MAX_RUNNER_BOBSERVERS_HF0"] = FIBERCHAIN_MAX_RUNNER_BOBSERVERS_HF0;
   result["FIBERCHAIN_MAX_SHARE_SUPPLY"] = FIBERCHAIN_MAX_SHARE_SUPPLY;
   result["FIBERCHAIN_MAX_SIG_CHECK_DEPTH"] = FIBERCHAIN_MAX_SIG_CHECK_DEPTH;
   result["FIBERCHAIN_MAX_TIME_UNTIL_EXPIRATION"] = FIBERCHAIN_MAX_TIME_UNTIL_EXPIRATION;
   result["FIBERCHAIN_MAX_TRANSACTION_SIZE"] = FIBERCHAIN_MAX_TRANSACTION_SIZE;
   result["FIBERCHAIN_MAX_UNDO_HISTORY"] = FIBERCHAIN_MAX_UNDO_HISTORY;
   result["FIBERCHAIN_MAX_VOTED_BOBSERVERS_HF0"] = FIBERCHAIN_MAX_VOTED_BOBSERVERS_HF0;
   result["FIBERCHAIN_MAX_BOBSERVER_URL_LENGTH"] = FIBERCHAIN_MAX_BOBSERVER_URL_LENGTH;
   result["FIBERCHAIN_MIN_ACCOUNT_NAME_LENGTH"] = FIBERCHAIN_MIN_ACCOUNT_NAME_LENGTH;
   result["FIBERCHAIN_MIN_BLOCK_SIZE"] = FIBERCHAIN_MIN_BLOCK_SIZE;
   result["FIBERCHAIN_MIN_BLOCK_SIZE_LIMIT"] = FIBERCHAIN_MIN_BLOCK_SIZE_LIMIT;
   result["FIBERCHAIN_MIN_PERMLINK_LENGTH"] = FIBERCHAIN_MIN_PERMLINK_LENGTH;
   result["FIBERCHAIN_MIN_REPLY_INTERVAL"] = FIBERCHAIN_MIN_REPLY_INTERVAL;
   result["FIBERCHAIN_MIN_ROOT_COMMENT_INTERVAL"] = FIBERCHAIN_MIN_ROOT_COMMENT_INTERVAL;
   result["FIBERCHAIN_MIN_VOTE_INTERVAL_SEC"] = FIBERCHAIN_MIN_VOTE_INTERVAL_SEC;
   result["FIBERCHAIN_MINER_ACCOUNT"] = FIBERCHAIN_MINER_ACCOUNT;
   result["FIBERCHAIN_MINING_TIME"] = FIBERCHAIN_MINING_TIME;
   result["FIBERCHAIN_MIN_UNDO_HISTORY"] = FIBERCHAIN_MIN_UNDO_HISTORY;
   result["FIBERCHAIN_NULL_ACCOUNT"] = FIBERCHAIN_NULL_ACCOUNT;
   result["FIBERCHAIN_NUM_INIT_MINERS"] = FIBERCHAIN_NUM_INIT_MINERS;
   result["FIBERCHAIN_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = FIBERCHAIN_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["FIBERCHAIN_OWNER_AUTH_RECOVERY_PERIOD"] = FIBERCHAIN_OWNER_AUTH_RECOVERY_PERIOD;
   result["FIBERCHAIN_OWNER_UPDATE_LIMIT"] = FIBERCHAIN_OWNER_UPDATE_LIMIT;
   result["FIBERCHAIN_ROOT_POST_PARENT"] = FIBERCHAIN_ROOT_POST_PARENT;
   result["FIBERCHAIN_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = FIBERCHAIN_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["FIBERCHAIN_SOFT_MAX_COMMENT_DEPTH"] = FIBERCHAIN_SOFT_MAX_COMMENT_DEPTH;
   result["FIBERCHAIN_START_MINER_VOTING_BLOCK"] = FIBERCHAIN_START_MINER_VOTING_BLOCK;
   result["PIA_SYMBOL"] = PIA_SYMBOL;
   result["FIBERCHAIN_TEMP_ACCOUNT"] = FIBERCHAIN_TEMP_ACCOUNT;
   result["FIBERCHAIN_TRANSFER_SAVINGS_MAX_MONTH"] = FIBERCHAIN_TRANSFER_SAVINGS_MAX_MONTH;
   result["FIBERCHAIN_TRANSFER_SAVINGS_CYCLE"] = FIBERCHAIN_TRANSFER_SAVINGS_CYCLE;
   result["FIBERCHAIN_DEPOSIT_FUND_NAME"] = FIBERCHAIN_DEPOSIT_FUND_NAME;
   result["FIBERCHAIN_DEPOSIT_COUNT_LIMIT"] = FIBERCHAIN_DEPOSIT_COUNT_LIMIT;
   result["FIBERCHAIN_EXCHANGE_MIN_BALANCE "] = FIBERCHAIN_EXCHANGE_MIN_BALANCE;
   result["FIBERCHAIN_EXCHANGE_FEE "] = FIBERCHAIN_EXCHANGE_FEE;
   result["FIBERCHAIN_EXCHANGE_FEE_OWNER"] = FIBERCHAIN_EXCHANGE_FEE_OWNER;
   result["FIBERCHAIN_DAPP_TRANSACTION_FEE"] = FIBERCHAIN_DAPP_TRANSACTION_FEE;

   return result;
}

} } // fiberchain::protocol
